apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argorollout-chart
  namespace: {{ .Values.namespace }}
  labels:
    app: argorollout-chart
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: argorollout-chart
  template:
    metadata:
      labels:
        app: argorollout-chart
    spec:
      containers:
        - name: argorollout-chart
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
  strategy:
    canary:
      {{- toYaml .Values.strategy.canary | nindent 6 }}
