apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argo-nginx
  namespace: {{ .Values.namespace }}
  labels:
    app: argo-nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: argo-nginx
  template:
    metadata:
      labels:
        app: argo-nginx
    spec:
      containers:
        - name: argo-nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
  strategy:
    canary:
      {{- toYaml .Values.strategy.canary | nindent 6 }}
